before_script:
  - git remote set-url origin git@git.sami.int.thomsonreuters.com:pandora/pandora-publish-doccloud.git
  - git pull origin master
  - npm install

test:
  stage: test
  tags:
    - node
    - windows
  script:
    - call grunt lint
    - call grunt test
  except:
    - tags
    - release

release:
  stage: deploy
  tags:
    - node
    - linux
  script:
    - tagver patch
    - npm version from-git
    - bamsu --url=emea/default.npm.local/pandora-book-plugin/
  only:
    - master
